run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

  disable-all: true

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable:
      - shadow
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
    - pkg/generated
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
