# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        args: [-s]  # Add simplify flag
      - id: go-imports
      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: go-build
        name: go build
        entry: go build ./...
        language: system
        files: '\.go$'
        pass_filenames: false
      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        files: '\.go$'
        pass_filenames: false
      - id: go-mod-verify
        name: go mod verify
        entry: go mod verify
        language: system
        files: 'go\.mod$'
        pass_filenames: false
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        files: '\.go$'
        pass_filenames: false
