apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: rebalance
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/ssccio/rebalance
  shortDescription: Rebalance pods across nodes by controlled eviction
  description: |
    This plugin evicts pods from heavily loaded nodes to trigger rescheduling
    on less loaded nodes. It's particularly useful after node failures or 
    when nodes rejoin a cluster and the pod distribution becomes uneven.
    
    The plugin can use CPU/memory metrics (requires metrics-server) or fall
    back to pod count for determining node load.
  caveats: |
    * Requires pod eviction permissions
    * For CPU/memory metrics, requires metrics-server
    * Respects PodDisruptionBudgets when evicting
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/ssccio/rebalance/releases/download/{{ .TagName }}/kubectl-rebalance_{{ .TagName }}_Darwin_x86_64.tar.gz
    sha256: "{{ .Sha256 }}"
    bin: kubectl-rebalance
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/ssccio/rebalance/releases/download/{{ .TagName }}/kubectl-rebalance_{{ .TagName }}_Darwin_arm64.tar.gz
    sha256: "{{ .Sha256 }}"
    bin: kubectl-rebalance
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/ssccio/rebalance/releases/download/{{ .TagName }}/kubectl-rebalance_{{ .TagName }}_Linux_x86_64.tar.gz
    sha256: "{{ .Sha256 }}"
    bin: kubectl-rebalance
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/ssccio/rebalance/releases/download/{{ .TagName }}/kubectl-rebalance_{{ .TagName }}_Linux_arm64.tar.gz
    sha256: "{{ .Sha256 }}"
    bin: kubectl-rebalance
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/ssccio/rebalance/releases/download/{{ .TagName }}/kubectl-rebalance_{{ .TagName }}_Windows_x86_64.zip
    sha256: "{{ .Sha256 }}"
    bin: kubectl-rebalance.exe