name: Update README

on:
  workflow_run:
    workflows: ["CI", "Release"]
    types:
      - completed
  push:
    branches: [ main, master ]
    paths:
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate TOC
      uses: technote-space/toc-generator@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit changes
      if: steps.toc.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "docs: update TOC"
        git push