name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Debug directory structure
      run: |
        pwd
        ls -la
        ls -la cmd/ || echo "cmd directory not found"
        find . -name "*.go" -type f | head -20

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...
    - name: Run tests
      run: go test -v -race ./...

    - name: Build
      run: go build -v ./cmd/kubectl-rebalance

    - name: Test build
      run: ./kubectl-rebalance --help

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.21', '1.22']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Debug directory structure
      run: |
        pwd
        ls -la
        ls -la cmd/ || echo "cmd directory not found"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v -o kubectl-rebalance ./cmd/kubectl-rebalance

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kubectl-rebalance-${{ matrix.os }}-go${{ matrix.go }}
        path: kubectl-rebalance
