name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Go tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - uses: pre-commit/action@v3.0.0
